# DOCUMENT CLUSTERING WITH DAILY KOS
dailykos = read.csv("dailykos.csv")
dim(dailykos)
distances <- dist(dailykos, method = "euclidean")
dendo <- hclust(distances, method = "ward.D")
plot(dendo)
cluster <- cutree(dendo, k = 7)
table(cluster)
mysummary <- function (i) {
  HierClusteri <- subset(dailykos, cluster==i)
  tail(sort(colMeans(HierClusteri)))
}
mysummary(1)
mysummary(2)
mysummary(3)
mysummary(4)
mysummary(5)
mysummary(6)
mysummary(7)
set.seed(1000)
kmeans <- kmeans(dailykos, 7)
table(kmeans$cluster)
kmeanssummary <- function(i) {
  KmeansClusteri = subset(dailykos, kmeans$cluster == i)
  tail(sort(colMeans(KmeansClusteri)))
}
kmeanssummary(1)
kmeanssummary(2)
kmeanssummary(3)
kmeanssummary(4)
kmeanssummary(5)
kmeanssummary(6)
kmeanssummary(7)
table(cluster, kmeans$cluster)

# MARKET SEGMENTATION FOR AIRLINES
airlines = read.csv("AirlinesCluster.csv")
summary(airlines)
library(caret)
preproc = preProcess(airlines)
airlinesNorm = predict(preproc, airlines)
summary(airlinesNorm)
distances1 <- dist(airlinesNorm, method = "euclidean")
dendo1 <- hclust(distances1, method = "ward.D")
plot(dendo1)
cluster1 <- cutree(dendo1, k = 5)
table(cluster1)
names(airlines)
tapply(airlines$Balance, cluster1, mean)
tapply(airlines$QualMiles, cluster1, mean)
tapply(airlines$BonusMiles, cluster1, mean)
tapply(airlines$BonusTrans, cluster1, mean)
tapply(airlines$FlightMiles, cluster1, mean)
tapply(airlines$FlightTrans, cluster1, mean)
tapply(airlines$DaysSinceEnroll, cluster1, mean)
set.seed(88)
kmeans1 <- kmeans(airlines, centers = 5, iter.max = 1000)
table(kmeans1$cluster)
kmeans1$centers

# PREDICTING STOCK RETURNS WITH CLUSTER-THEN-PREDICT
stocks <- read.csv("StocksCluster.csv")
dim(stocks)
head(stocks)
summary(stocks$PositiveDec)
cor(stocks)
lapply(stocks, mean)
set.seed(144)
install.packages("caTools")
library(caTools)
spl = sample.split(stocks$PositiveDec, SplitRatio = 0.7)
stocksTrain = subset(stocks, spl == TRUE)
stocksTest = subset(stocks, spl == FALSE)
logit <- glm(PositiveDec~., data = stocksTrain, family = binomial)
trainpredict <- predict(logit, newdata = stocksTrain, type = "response")
trainpredict <- ifelse(trainpredict > 0.5, 1, 0)
table(trainpredict, stocksTrain$PositiveDec)
(990+3640)/nrow(stocksTrain)
testpredict <- predict(logit, newdata = stocksTest, type = "response")
testpredict <- ifelse(testpredict > 0.5, 1, 0)
table(testpredict, stocksTest$PositiveDec)
(417+1553)/nrow(stocksTest)
(344+1553)/nrow(stocksTest)
limitedTrain = stocksTrain
limitedTrain$PositiveDec = NULL
limitedTest = stocksTest
limitedTest$PositiveDec = NULL
preproc = preProcess(limitedTrain)
normTrain = predict(preproc, limitedTrain)
normTest = predict(preproc, limitedTest)
summary(normTrain)
summary(normTest)
set.seed(144)
km <- kmeans(normTrain, centers = 3)
table(km$cluster)
library(flexclust)
km.kcca = as.kcca(km, normTrain)
clusterTrain = predict(km.kcca)
clusterTest = predict(km.kcca, newdata=normTest)
table(clusterTest)
stocksTrain1 = subset(stocksTrain, clusterTrain == 1)
stocksTrain2 = subset(stocksTrain, clusterTrain == 2)
stocksTrain3 = subset(stocksTrain, clusterTrain == 3)
stocksTest1 = subset(stocksTest, clusterTest == 1)
stocksTest2 = subset(stocksTest, clusterTest == 2)
stocksTest3 = subset(stocksTest, clusterTest == 3)
mean(stocksTrain1$PositiveDec)
mean(stocksTrain2$PositiveDec)
mean(stocksTrain3$PositiveDec)
StocksModel1 <- glm(PositiveDec~., data = stocksTrain1, family = binomial)
StocksModel2 <- glm(PositiveDec~., data = stocksTrain2, family = binomial)
StocksModel3 <- glm(PositiveDec~., data = stocksTrain3, family = binomial)
coefficients(StocksModel1)
coefficients(StocksModel2)
coefficients(StocksModel3)
PredictTest1 <- predict(StocksModel1, newdata = stocksTest1, type = "response")
PredictTest2 <- predict(StocksModel2, newdata = stocksTest2, type = "response")
PredictTest3 <- predict(StocksModel3, newdata = stocksTest3, type = "response")
table(PredictTest1 > 0.5, stocksTest1$PositiveDec)
(774+30)/nrow(stocksTest1)
table(PredictTest2 > 0.5, stocksTest2$PositiveDec)
(388+757)/nrow(stocksTest2)
table(PredictTest3 > 0.5, stocksTest3$PositiveDec)
(49+13)/nrow(stocksTest3)
AllPredictions = c(PredictTest1, PredictTest2, PredictTest3)
AllOutcomes = c(stocksTest1$PositiveDec, stocksTest2$PositiveDec, stocksTest3$PositiveDec)
table(AllPredictions > 0.5, AllOutcomes)
(467+1544)/nrow(stocksTest)
